#ifndef GC_ANT_THREAD_SAFETY_TRAIN_SIDEBAR_H
#define GC_ANT_THREAD_SAFETY_TRAIN_SIDEBAR_H

#define RT_MODE_ERGO      0x0001
#define RT_MODE_SPIN      0x0002
#define RT_MODE_SLOPE     0x0002
#define RT_MODE_CALIBRATE 0x0004

#endif
